version: '3.9'

services:
  app:
    image: warapetchrpvs/nextjs-16.2-app:latest
    container_name: nextjs-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      
    environment:
      - NODE_ENV=production
      
    # ถ้าต้องการ mount โค้ดสำหรับ development (optional)
    volumes:
      - .:/app
      
      