# ในเครื่องเรา

services:
  app:
    build: .
    container_name: nextjs-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - WATCHPACK_POLLING_INTERVAL=1000
      - CHOKIDAR_USEPOLLING=true
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - .:/app
      - /app/node_modules

    command: npm run dev
    stdin_open: true
    tty: true